dlcs/iiif-presentation

src/IIIFPresentation/API.Tests/Integration/Infrastructure/HttpRequestMessageBuilder.cs, src/IIIFPresentation/API.Tests/Integration/ModifyCollectionTests.cs, src/IIIFPresentation/API/Attributes/EtagCachingAttribute.cs, src/IIIFPresentation/API/Infrastructure/Helpers/HttpRequestX.cs
Resolves #9 
This PR renames the `IIIF-CS-Show-Extra` header to `X-IIIF-CS-Show-Extras`
=> rename IIIF-CS-Show-Extra header

src/IIIFPresentation/API/Features/Storage/StorageController.cs
Partly resolves #17 
This PR moves hierarchical collects to use `.AsJson` found with iiif-net library over relying on internal serialization.
The reason for this change is that `.AsJson` contains a number of converters designed for the iiif spec which are not available through standard serialization.  Additionally, the `Content-Type` header is now correctly set to that required by the iiif spec
This Pr does not change `FlatCollection` as it's currently being modified to work with the iiif-net library in #7
=> Hierarchical collection to return with AsJson

src/IIIFPresentation/API/Program.cs
Resolves #21
This PR adds in some additional configuration to enable URL's in response bodies to use the `https` schema when accessed via AWS, as opposed to `http`
=> Adding headers to allow https in response

src/IIIFPresentation/API.Tests/Integration/GetCollectionTests.cs, src/IIIFPresentation/API.Tests/Integration/ModifyCollectionTests.cs, src/IIIFPresentation/API/Converters/CollectionConverter.cs, src/IIIFPresentation/API/Features/Storage/Helpers/PresentationContextX.cs, src/IIIFPresentation/API/Features/Storage/Helpers/RootCollection.cs, src/IIIFPresentation/API/Features/Storage/Requests/CreateCollection.cs, src/IIIFPresentation/API/Features/Storage/Requests/GetCollection.cs, src/IIIFPresentation/API/Features/Storage/Requests/UpdateCollection.cs, src/IIIFPresentation/API/Helpers/CollectionHelperX.cs, src/IIIFPresentation/API/Infrastructure/ControllerBaseX.cs, src/IIIFPresentation/Repository/Migrations/20240920085119_addingNewPk.Designer.cs, src/IIIFPresentation/Repository/Migrations/20240920085119_addingNewPk.cs, src/IIIFPresentation/Repository/PresentationContext.cs, src/IIIFPresentation/Test.Helpers/Helpers/RootCollection.cs, src/IIIFPresentation/Test.Helpers/Integration/PresentationContextFixture.cs
Resolves #23
This PR updates flat collections to refer to the root collection as root everywhere. This includes when gathering parent collections.
How this works is that the primary key of the `collections` table has changed to a composite key of `customer id` and `id`, meaning that the root record of the customer will always have an id of `root`.  The knock-on effect of this is a simplification in how we work out the root collection, as there is now not a separate internal id that is referred to as `root` by customers
=> Modify collection table to expose root collection as root

src/IIIFPresentation/API.Tests/Integration/ModifyCollectionTests.cs, src/IIIFPresentation/API/Features/Storage/Requests/CreateCollection.cs
Resolves https://github.com/dlcs/iiif-presentation/issues/39
This PR fixes a minor bug that caused a slight difference between the `created` and `modified` timestamps on a newly created collection, caused by calling `DateTime.UtcNow` twice.
=> Ensure matching 'modified' and 'creation' collection values on create

src/IIIFPresentation/Repository/Helpers/CollectionRetrieval.cs
Resolves #48
This PR fixes a minor bug where `CollectionRetrieval.RetrieveFullPathForCollection` wasn't including slashes between slugs in the generated path.
=> Update 'RetrieveFullPathForCollection' to return correct paths

src/IIIFPresentation/API.Tests/Integration/GetCollectionTests.cs, src/IIIFPresentation/API.Tests/Integration/ModifyCollectionTests.cs, src/IIIFPresentation/API/Converters/CollectionConverter.cs, src/IIIFPresentation/API/Features/Storage/Helpers/PresentationContextX.cs, src/IIIFPresentation/API/Features/Storage/Requests/CreateCollection.cs, src/IIIFPresentation/API/Features/Storage/Requests/UpsertCollection.cs, src/IIIFPresentation/Core/Helpers/DateTimeX.cs, src/IIIFPresentation/Models/API/Collection/PresentationCollection.cs
=> Round down the timestamps returned to the whole second for PresentationCollection

src/IIIFPresentation/API.Tests/API.Tests.csproj, src/IIIFPresentation/API.Tests/Infrastructure/SqidsGeneratorTests.cs, src/IIIFPresentation/API.Tests/Integration/ModifyCollectionTests.cs, src/IIIFPresentation/API/API.csproj, src/IIIFPresentation/API/Features/Storage/Requests/CreateCollection.cs, src/IIIFPresentation/API/Helpers/CollectionHelperX.cs, src/IIIFPresentation/API/Infrastructure/IdGenerator/IIdGenerator.cs, src/IIIFPresentation/API/Infrastructure/IdGenerator/SqidsGenerator.cs, src/IIIFPresentation/API/Infrastructure/ServiceCollectionX.cs, src/IIIFPresentation/API/Program.cs
Resolves #25 
this PR creates an id generator that can be injected into the context to create more human readable id's.
=> Change id's to be generated by sqids and an injected id generator

src/IIIFPresentation/API.Tests/Integration/ModifyCollectionTests.cs, src/IIIFPresentation/API/Features/Storage/Helpers/PresentationContextX.cs, src/IIIFPresentation/API/Features/Storage/Requests/CreateCollection.cs, src/IIIFPresentation/API/Features/Storage/Requests/UpsertCollection.cs, src/IIIFPresentation/API/Infrastructure/ControllerBaseX.cs, src/IIIFPresentation/API/Infrastructure/PresentationController.cs, src/IIIFPresentation/API/Infrastructure/Requests/ModifyEntityResult.cs, src/IIIFPresentation/Models/API/General/DeleteCollectionType.cs, src/IIIFPresentation/Models/API/General/ModifyCollectionType.cs, src/IIIFPresentation/Repository/Helpers/CollectionRetrieval.cs
Resolves #32 
This PR updates the `PUT` method to be able to detect when a possible circular reference is created between a parent and child record
Additionally, this PR also introduces error codes for modify/create collections in a similar manner to delete
=> Adding ability to detect when updating a collection might create a circular reference

src/IIIFPresentation/API.Tests/Integration/GetCollectionTests.cs, src/IIIFPresentation/API.Tests/Integration/ModifyCollectionTests.cs, src/IIIFPresentation/API/Features/Storage/Models/CollectionWithItems.cs, src/IIIFPresentation/API/Features/Storage/Requests/CreateCollection.cs, src/IIIFPresentation/API/Features/Storage/Requests/GetHierarchicalCollection.cs, src/IIIFPresentation/API/Features/Storage/StorageController.cs, src/IIIFPresentation/Models/API/General/ModifyCollectionType.cs, src/IIIFPresentation/Test.Helpers/Integration/LocalStackFixture.cs, src/IIIFPresentation/Test.Helpers/Integration/PresentationContextFixture.cs
Resolves #26 
This PR is the retrieval side of #26, and allows IIIF collections on the GET hierarchical path.
Additionally, this PR modifies `POST` to verify that the collection is a valid IIIF collection and strips out extra properties
=> Add ability to retrieve a IIIF collection from S3

src/IIIFPresentation/API.Tests/Integration/GetCollectionTests.cs, src/IIIFPresentation/API/Features/Storage/StorageController.cs, src/IIIFPresentation/API/Infrastructure/ControllerBaseX.cs
This PR fixes a bug where storage collection queries specifying `orderByDescending={field_name}` would only order items by the creation date, regardless of which field was specified.
It also updates the valid 'orderByDescending' test in `GetCollectionTests` to expect a different item when dealing with the `slug` and `id` fields, as they are now sorted alphabetically.
=> Fix `orderByDescending` behaviour

src/IIIFPresentation/API.Tests/Integration/ModifyCollectionTests.cs, src/IIIFPresentation/API/Features/Storage/Helpers/ErrorHelper.cs, src/IIIFPresentation/API/Features/Storage/Requests/CreateCollection.cs, src/IIIFPresentation/API/Features/Storage/Requests/GetHierarchicalCollection.cs, src/IIIFPresentation/API/Features/Storage/Requests/PostHierarchicalCollection.cs, src/IIIFPresentation/API/Features/Storage/Requests/UpsertCollection.cs, src/IIIFPresentation/API/Features/Storage/StorageController.cs, src/IIIFPresentation/API/Helpers/CollectionHelperX.cs, src/IIIFPresentation/Models/API/Collection/Upsert/UpsertFlatCollection.cs
Resolves #57
This PR allows thumbnails to be correctly converted between `ExternalResource` and `string` when using POST on a IIIF collection, via a `collections`
=> Thumbnail can't handle IIIF style thumbnail on POST

src/IIIFPresentation/API/Features/Storage/Requests/UpsertCollection.cs
This PR fixes a bug that prevented storage collections created via PUT from being read via their hierarchal URL, caused by `UpsertCollectionHandler` setting the default hierarchy type to `ResourceType.IIIFCollection`.
=> Initialize hierarchy with `StorageCollection` type in `UpsertCollection` 

src/IIIFPresentation/API.Tests/Integration/ModifyCollectionTests.cs, src/IIIFPresentation/API/Features/Storage/Requests/CreateCollection.cs, src/IIIFPresentation/API/Features/Storage/Requests/UpsertCollection.cs
Fixes #108 
- **Use resolved parent id instead of whatever is provided in request**
- **Add verification to weed out hierarchical URIs for parents in create/update**
Covered all 4 cases (create/update with full flat URIs and full hierarchical URIs), seem to do the trick.
=> Fix for #108 - handle full URI parents

src/IIIFPresentation/API.Tests/Integration/ModifyManifestTests.cs, src/IIIFPresentation/Core/IIIF/IIIFResponseX.cs
Different invalid payloads could result in different exception types from Newtonsoft. e.g.
`{"id": "123` - `JsonReaderException`
`{"id": "123"` - `JsonSerializationException`
Catch base exception `JsonException` instead as both inherit from this.
Change introduced in #116
=> Better error handling when deserializing IIIF Json

src/IIIFPresentation/API.Tests/Converters/ManifestConverterTests.cs, src/IIIFPresentation/API.Tests/Helpers/CollectionHelperXTests.cs, src/IIIFPresentation/API.Tests/Infrastructure/Validation/PresentationValidationTests.cs, src/IIIFPresentation/API.Tests/Integration/ModifyManifestTests.cs, src/IIIFPresentation/API/Converters/ManifestConverter.cs, src/IIIFPresentation/API/Features/Manifest/Requests/CreateManifest.cs, src/IIIFPresentation/API/Features/Storage/Requests/CreateCollection.cs, src/IIIFPresentation/API/Features/Storage/Requests/UpsertCollection.cs, src/IIIFPresentation/API/Helpers/CollectionHelperX.cs, src/IIIFPresentation/API/Infrastructure/Validation/PresentationValidation.cs
Follows on from #116 - which was rebased onto `main` after #110 had been merged. The latter introduced logic for validating hierarchical parent, this change adds that to `Manifest` handling and refactors to a common helper.
Introduces new `IPresentation.IsUriParentInvalid()` helper which encapsulates this logic.
Also resolves issue where `Manifest.Parent` was returning Id only, rather than Flat path.
=> Validate hierarchical manifest parent

src/IIIFPresentation/API.Tests/Integration/ModifyCollectionTests.cs, src/IIIFPresentation/API/Features/Storage/Requests/PostHierarchicalCollection.cs, src/IIIFPresentation/Repository.Tests/Helpers/CollectionRetrievalTests.cs, src/IIIFPresentation/Repository/Helpers/CollectionRetrieval.cs
Fixes #119. Issue was how slug was concatenated, slash was missing meaning all path segments were concatenated. Using examples from ticket:
* `/nest_test_a` - resulted in looking for parent with slug `""` (root)
* `/nest_test_a/nest_test_b` - resulted in looking for parent with slug `"nest_test_a"` (created above).
* `/nest_test_a/nest_test_b/nest_test_c` - resulted in looking for parent with slug `"nest_test_bnest_test_c"` as segments were joined with `string.Empty` which was not found. Fix is to concatenate elements with `"/"` so we now look for `"nest_test_b/nest_test_c"`
Also added missing tests for `RetrieveHierarchy`
=> Fix bug preventing deeper nested hierach collection creation

src/IIIFPresentation/API.Tests/Integration/ModifyCollectionTests.cs, src/IIIFPresentation/API/Features/Storage/Requests/PostHierarchicalCollection.cs, src/IIIFPresentation/API/Infrastructure/AWS/IIIFS3Service.cs, src/IIIFPresentation/Core.Tests/Helpers/CollectionXTests.cs, src/IIIFPresentation/Core/Helpers/CollectionX.cs
Set `@context` and remove any known presentation behaviours when writing to S3.
Also modified `PostHierarchicalCollection` to use some reusable methods/classes introduced in previous PRs (ie `.ConvertCollectionToIIIF()` and `IIIFS3Service`).
Fixes #125
=> Fix bug where hierarchical collection has no context

src/IIIFPresentation/API.Tests/Features/CustomerCreation/CustomerCreationMessageHandlerTests.cs, src/IIIFPresentation/API/Features/CustomerCreation/CustomerCreatedListenerService.cs, src/IIIFPresentation/API/Features/CustomerCreation/CustomerCreatedMessage.cs, src/IIIFPresentation/API/Features/CustomerCreation/CustomerCreatedMessageHandler.cs, src/IIIFPresentation/API/Features/Storage/Requests/DeleteCollection.cs, src/IIIFPresentation/API/Infrastructure/ServiceCollectionX.cs, src/IIIFPresentation/API/KnownCollections.cs, src/IIIFPresentation/API/Program.cs, src/IIIFPresentation/AWS/AWS.csproj, src/IIIFPresentation/AWS/Configuration/AWSConfiguration.cs, src/IIIFPresentation/AWS/SQS/IMessageHandler.cs, src/IIIFPresentation/AWS/SQS/QueueMessage.cs, src/IIIFPresentation/AWS/SQS/SqsListener.cs, src/IIIFPresentation/AWS/SQS/SqsQueueUtilities.cs, src/IIIFPresentation/AWS/Settings/AWSSettings.cs, src/IIIFPresentation/AWS/Settings/SQSSettings.cs, src/IIIFPresentation/Core/Helpers/GuardX.cs
Add SQS listener for 'customer created' notification from Protagonist, on receipt ensure a Root collection exists for customer. Implementation is basically a `BackgroundWorker` in the API project, handling logic is all in `CustomerCreatedMessageHandler`.
Lots of this PR is boilerplate for SQS listening, based on previous project.
Note that if the SQS queue name setting isn't set the background worker won't run - this can be default in dedicated instances or for local dev.
Related (publishing side) - https://github.com/dlcs/protagonist/pull/914
=> Handle customer created

src/IIIFPresentation/API.Tests/Converters/CollectionConverterTests.cs, src/IIIFPresentation/API.Tests/Integration/GetCollectionTests.cs, src/IIIFPresentation/API/Converters/CollectionConverter.cs
This PR adds `behavior sections` to items in retrieve by flat URL's so that storage collections and IIIF collections can be distinguished by the UI
I.E.:
```json
{
"publicId": "https://localhost:7230/1",
"slug": "",
"items": [
{
"id": "https://localhost:7230/1/collections/swq5jt88zov1p1pbbpa",
"type": "Collection",
"label": {
"en": [
"post testing"
]
}
}
]
}
```
becomes
```json
{
"publicId": "https://localhost:7230/1",
"slug": "",
"items": [
{
"id": "https://localhost:7230/1/collections/swq5jt88zov1p1pbbpa",
"type": "Collection",
"label": {
"en": [
"post testing"
]
},
"behavior": [
"public-iiif",
"storage-collection"
]
}
]
}
```
=> Add behavior to items in collection retrieval calls

src/IIIFPresentation/API.Tests/Helpers/CollectionHelperXTests.cs, src/IIIFPresentation/API.Tests/Integration/GetManifestTests.cs, src/IIIFPresentation/API.Tests/Integration/ModifyManifestCreateTests.cs, src/IIIFPresentation/API.Tests/Integration/ModifyManifestUpdateTests.cs, src/IIIFPresentation/API/Converters/ManifestConverter.cs, src/IIIFPresentation/API/Features/Manifest/ManifestService.cs, src/IIIFPresentation/API/Features/Manifest/Requests/GetManifest.cs, src/IIIFPresentation/API/Helpers/CollectionHelperX.cs, src/IIIFPresentation/Models/API/Manifest/PresentationManifest.cs
Manifest will return `publicId` property from:
* GET flat
* POST flat
* PUT flat
Note - I've intentionally used `dbManifest.Hierarchy.Single()` knowing it will break when we add handling for non-canonical paths. Felt safer to get an upfront error than possibly miss some logic.
=> Flat manifest gains public_id

src/IIIFPresentation/API.Tests/Attributes/ETagCachingAttributeTests.cs, src/IIIFPresentation/API.Tests/Integration/GetManifestTests.cs, src/IIIFPresentation/API/Attributes/EtagCachingAttribute.cs
Background: right now browsers will cache IIIF resources to disk for the caching period before checking if new content is available. That means we're never sending up an `If-None-Match` and getting a corresponding 304, so we end up with stale data in the browser. This change makes clients always send an `If-None-Match` before using the local cache.
Related to https://github.com/dlcs/iiif-presentation/issues/140
=> Set Cache-Control: no-cache for responses with an ETag

src/IIIFPresentation/API.Tests/Attributes/ETagCachingAttributeTests.cs, src/IIIFPresentation/API/Attributes/EtagCachingAttribute.cs
This is a temporary workaround for ETags being missing on larger responses (first 20KB, now 256KB). I've investigated what's involved in propagating the ETag from S3 and unfortunately it's not that simple due to:
```csharp
manifest = manifest.SetGeneratedFields(dbManifest, request.UrlRoots,
m => m.Hierarchy!.Single(h => h.Canonical));
```
We modify the manifest after we get it from S3 with fields from the database -- so the ETag isn't guaranteed to be a valid checksum.
=> Generate ETags for responses unconditionally

src/IIIFPresentation/API.Tests/Integration/DeleteManifestTests.cs, src/IIIFPresentation/API.Tests/Integration/DeleteManifestUpdateTests.cs, src/IIIFPresentation/API/Features/Manifest/ManifestController.cs, src/IIIFPresentation/API/Features/Manifest/Requests/DeleteManifest.cs, src/IIIFPresentation/API/Infrastructure/PresentationController.cs, src/IIIFPresentation/Models/API/General/DeleteManifestType.cs
Based on existing code for collections, with simplification as manifests (rn) don't need to worry about their items, afaik.
Added tests for the expected set of responses (forbidden, not found or success: no content)
=> #150 - delete manifest - implement + tests

src/IIIFPresentation/API.Tests/Converters/CollectionConverterTests.cs, src/IIIFPresentation/API.Tests/Helpers/PresentationX.cs, src/IIIFPresentation/API.Tests/Infrastructure/Validation/PresentationValidationTests.cs, src/IIIFPresentation/API.Tests/Integration/GetCollectionTests.cs, src/IIIFPresentation/API.Tests/Integration/GetManifestTests.cs, src/IIIFPresentation/API.Tests/Integration/ModifyManifestCreateTests.cs, src/IIIFPresentation/API.Tests/Integration/ModifyManifestUpdateTests.cs, src/IIIFPresentation/API/Converters/CollectionConverter.cs, src/IIIFPresentation/API/Converters/ManifestConverter.cs, src/IIIFPresentation/API/Features/Storage/Helpers/PresentationCollectionX.cs, src/IIIFPresentation/Models/API/Collection/PresentationCollection.cs, src/IIIFPresentation/Models/API/IPresentation.cs, src/IIIFPresentation/Models/API/Manifest/PresentationManifest.cs
`"flatId"` is now output on `PresentationManifest` and `PresentationCollection` objects. 
This saves parsing the `"id"` to get the last slug, for now they match but could differ in the future.
=> PresentationManifest and Collection gain FlatId

src/IIIFPresentation/API/API.csproj, src/IIIFPresentation/Core/Core.csproj, src/IIIFPresentation/Models/Models.csproj, src/IIIFPresentation/Repository/Repository.csproj
Bump iiif-net to latest version, specifically looking for improved deserialization of Service elements that we don't have strongly typed models for. 
Brings in changes introduced in the following versions of iiif-net:
* https://github.com/digirati-co-uk/iiif-net/releases/tag/v0.3.1
* https://github.com/digirati-co-uk/iiif-net/releases/tag/v0.3.0
=> Bump iiif-net package

src/IIIFPresentation/API.Tests/Integration/GetCollectionTests.cs, src/IIIFPresentation/API/Features/Storage/Helpers/PresentationContextX.cs
...because it means the page/pageSize could be out of bounds
=> When no items returned, set totalItems from db

src/IIIFPresentation/API.Tests/Integration/GetCollectionTests.cs, src/IIIFPresentation/API.Tests/Integration/GetManifestTests.cs, src/IIIFPresentation/API/Program.cs
- **#164 trailing slash tests**
- **Set global redirect rule to remove trailing slash**
Note, that if we happen to require more granular controls there's 1001 ways to do this, but I didn't want to overengineer sth that might never be needed.
=> Fix #164 - Redirect trailing slash

src/IIIFPresentation/API.Tests/Converters/CollectionConverterTests.cs, src/IIIFPresentation/API.Tests/Integration/GetCollectionTests.cs, src/IIIFPresentation/API.Tests/Integration/ModifyCollectionTests.cs, src/IIIFPresentation/API/Converters/CollectionConverter.cs, src/IIIFPresentation/API/Features/Manifest/ManifestService.cs, src/IIIFPresentation/API/Features/Storage/CollectionController.cs, src/IIIFPresentation/API/Features/Storage/Helpers/PresentationCollectionX.cs, src/IIIFPresentation/API/Features/Storage/Helpers/PresentationContextX.cs, src/IIIFPresentation/API/Features/Storage/Models/CollectionWithItems.cs, src/IIIFPresentation/API/Features/Storage/Requests/CreateCollection.cs, src/IIIFPresentation/API/Features/Storage/Requests/DeleteCollection.cs, src/IIIFPresentation/API/Features/Storage/Requests/GetCollection.cs, src/IIIFPresentation/API/Features/Storage/Requests/GetHierarchicalCollection.cs, src/IIIFPresentation/API/Features/Storage/Requests/UpsertCollection.cs, src/IIIFPresentation/API/Features/Storage/StorageController.cs, src/IIIFPresentation/API/Properties/launchSettings.json, src/IIIFPresentation/Models/Database/Collections/Collection.cs, src/IIIFPresentation/Models/Database/General/Hierarchy.cs, src/IIIFPresentation/Repository/Migrations/20241206173850_Hierarchy parent fk.Designer.cs, src/IIIFPresentation/Repository/Migrations/20241206173850_Hierarchy parent fk.cs, src/IIIFPresentation/Repository/Migrations/20241210091216_Hierarchy parent fk.Designer.cs, src/IIIFPresentation/Repository/Migrations/20241210091216_Hierarchy parent fk.cs, src/IIIFPresentation/Repository/Migrations/PresentationContextModelSnapshot.cs, src/IIIFPresentation/Repository/PresentationContext.cs
Fixes #166 and #167
Introduced a couple of navigation properties; `Hierarchy` gains `ParentCollection` and `Collection` gains `Children`. It's unlikely that the latter will be used but it's there should we need it. The former allows us to load the parent of the current collection when rendering collection to set the `"partOf"` - previously it was using current collections label and redirecting to parent hierarchical path - now it's using parent label and parent flat-id.
Renamed `ToFlatCollection` to `ToPresentationCollection` to reflect the name of the return type.
This was adding a bool to `RetrieveCollectionItems` in `GetHierarchicalCollection` but also slightly refactored this:
* Rather than checking if collection is public or not in calling controller, encapsulate that logic in the …
=> Bugfixes - correct partOf and hide non-public items

src/IIIFPresentation/API.Tests/Features/Manifest/Validators/PresentationManifestValidatorTests.cs, src/IIIFPresentation/API.Tests/Integration/ModifyManifestCreateTests.cs, src/IIIFPresentation/API.Tests/Integration/ModifyManifestUpdateTests.cs, src/IIIFPresentation/API.Tests/appsettings.Testing.json, src/IIIFPresentation/API/Features/Manifest/ManifestService.cs, src/IIIFPresentation/API/Features/Manifest/Validators/PresentationManifestValidator.cs, src/IIIFPresentation/API/Settings/ApiSettings.cs
Resolves #215
This PR changes manifests with painted resources and items present to ignore the painted resource section of a request, instead of responding with a bad request
=> Ignore painted resource when items are also present

src/IIIFPresentation/API.Tests/Features/Storage/Helpers/BehaviourXTests.cs, src/IIIFPresentation/API.Tests/Integration/ModifyCollectionTests.cs, src/IIIFPresentation/API.Tests/Integration/ModifyManifestAssetCreationTests.cs, src/IIIFPresentation/API/Features/Storage/Helpers/BehaviorX.cs, src/IIIFPresentation/API/Features/Storage/Helpers/ErrorHelper.cs, src/IIIFPresentation/Models/API/General/ModifyCollectionType.cs
resolves #165 
This PR creates a fallback value of `false` for `behavior` extension methods, causing them to not throw an error when `behavior` is null
=> Fix null behavior returning internal server error

src/IIIFPresentation/API.Tests/Integration/ModifyCollectionTests.cs, src/IIIFPresentation/API/Infrastructure/ControllerBaseX.cs, src/IIIFPresentation/Test.Helpers/Integration/TestContent.cs
Fixes #158 
- **Add unit test as per #158**
- **Use the created resource's Id field to provide Location**
This one is a bit weird - it seems like it assumed that the request was made directly to the resource, like with PUT, so it's probably due to some code unification in the past.
I see how in the future the modified bit of code can become a switch expression with anything specific, but I didn't want to overengineer it until we hit any further issues.
=> Fix #158 - Location header after created collection invalid

README.md
Resolves #223
Adds details for how a named query can be created to support the batch completion process
=> Add information for creating the batch named query

src/IIIFPresentation/API.Tests/Integration/ModifyManifestUpdateTests.cs, src/IIIFPresentation/API/Features/Manifest/ManifestController.cs, src/IIIFPresentation/API/Features/Storage/CollectionController.cs, src/IIIFPresentation/API/Features/Storage/Helpers/RequestBodyX.cs
Resolves #196
This PR updates PUT manifest to use the `TryDeserialize` method which improves handling of serialization errors so that a `BadRequest` is returned instead of an `InternalServerError`
=> Fixing serialization error to provide a nicer error

src/IIIFPresentation/API.Tests/Integration/ModifyManifestAssetCreationTests.cs, src/IIIFPresentation/API/Features/Manifest/ManifestService.cs, src/IIIFPresentation/API/Helpers/BatchHelper.cs
Implements #201 
As per clarifications on slack, changed the BadRequest response into "create space and continue" that leads to 201 Created.
- **Change order of operations to reduce risk of creating unused DLCS space**
- **Manifest-Asset-Post - Change test for prev behaviour into the updated one**
- **If asset with no space posted, create space**
=> Impl #201 - Create Space if manifest asset posted w/o space

src/IIIFPresentation/API.Tests/Converters/CollectionConverterTests.cs, src/IIIFPresentation/API.Tests/Integration/GetCollectionTests.cs, src/IIIFPresentation/API.Tests/Integration/ModifyCollectionTests.cs, src/IIIFPresentation/API/Converters/CollectionConverter.cs, src/IIIFPresentation/API/Features/Storage/Helpers/PresentationCollectionX.cs, src/IIIFPresentation/API/Features/Storage/Requests/CreateCollection.cs, src/IIIFPresentation/API/Features/Storage/Requests/UpsertCollection.cs, src/IIIFPresentation/Core.Tests/Helpers/CollectionXTests.cs, src/IIIFPresentation/Models/API/Collection/DescendantCounts.cs, src/IIIFPresentation/Models/API/Collection/PresentationCollection.cs, src/IIIFPresentation/Models/Database/Collections/Collection.cs
Add `"totals"` property to API Storage Collection results which returns the counts of immediate children by type.
Refactored `ToPresentationCollection` (used for GET) and `EnrichPresentationCollection` (used for POST and PUT) with the former now calling the latter. They both contained almost identical code, the difference being that the latter:
* Didn't set `Label` property. It will now always set `Label`
* Used `??=` for a few properties, meaning that the value returned is what was passed in body of request. However, the value saved to the DB could differ, meaning that a subsequent GET request would return different values. In practice I think the only property this could effect is `Behavior` (which I think isn't quite right as it prevents saving custom behaviors). The decision was to …
=> Include count of child items for storage-collection

src/IIIFPresentation/API.Tests/Converters/ManifestConverterTests.cs, src/IIIFPresentation/API.Tests/Integration/ModifyManifestAssetCreationTests.cs, src/IIIFPresentation/API/Converters/ManifestConverter.cs, src/IIIFPresentation/API/Features/Manifest/CanvasPaintingResolver.cs, src/IIIFPresentation/API/Features/Manifest/ManifestService.cs, src/IIIFPresentation/API/Features/Manifest/Requests/GetManifest.cs, src/IIIFPresentation/DLCS.Tests/API/DlcsApiClientTests.cs, src/IIIFPresentation/DLCS/API/DlcsApiClient.cs, src/IIIFPresentation/DLCS/API/DlcsHttpContent.cs, src/IIIFPresentation/DLCS/DlcsSettings.cs
#203 
- **Add ReadAsJson helper to handle not-deserialised responses from DLCS**
- **Add GetBatchAssets call to DLCS client**
- **Add ability to use provided asset dictionary during canvas painting supplementation in manifest create**
- **Code cleanup**
- **Test + fix for asset detail in manifest creation response**
=> Impl #203 - retrieve asset details from DLCS when responding to Create Manifest

src/IIIFPresentation/API.Tests/Converters/ManifestConverterTests.cs, src/IIIFPresentation/API/Converters/ManifestConverter.cs
Fixes #207 
Orders `paintedResources` by canvas then choice order.
=> Order paintedResources in manifests

src/IIIFPresentation/API.Tests/Converters/CollectionConverterTests.cs, src/IIIFPresentation/API.Tests/Features/Storage/Helpers/BehaviourXTests.cs, src/IIIFPresentation/API.Tests/Integration/DeleteCollectionTests.cs, src/IIIFPresentation/API.Tests/Integration/ModifyCollectionTests.cs, src/IIIFPresentation/API.Tests/Integration/ModifyManifestCreateTests.cs, src/IIIFPresentation/API/Converters/CollectionConverter.cs, src/IIIFPresentation/API/Features/Storage/Helpers/BehaviorX.cs, src/IIIFPresentation/AWS/Helpers/IIIFS3Service.cs, src/IIIFPresentation/Models/Infrastructure/Behavior.cs, src/IIIFPresentation/Models/Infrastucture/Behavior.cs
Fixes #168 
Add `"seeAlso"` to storage collections. Which values are shown is dependant on configuration, as noted in docs there is redundancy in these links until canonical paths are implemented.
=> Fix SeeAlso links for api storage collections

src/IIIFPresentation/API.Tests/Integration/GetManifestTests.cs, src/IIIFPresentation/API/Features/Manifest/ManifestReadService.cs, src/IIIFPresentation/API/Features/Manifest/ManifestWriteService.cs, src/IIIFPresentation/API/Features/Manifest/Requests/CreateManifest.cs, src/IIIFPresentation/API/Features/Manifest/Requests/GetManifest.cs, src/IIIFPresentation/API/Features/Manifest/Requests/UpsertManifest.cs, src/IIIFPresentation/API/Program.cs, src/IIIFPresentation/Test.Helpers/Helpers/DatabaseTestDataPopulation.cs
Reason for change was to populate `"assets"` on manifest GET with full details from DLCS. 
Refactored some classes to accomodate this:
* Renamed `ManifestService` -> `ManifestWriteService` and introduced an interface
* Moves `GetAssets` from `ManifestService` to a new class, `ManifestReadService`, to allow it to be shared
* Refactored code from `GetManifest` handler into `ManifestReadService`, and updated it to call `GetAssets` to read Asset data from DLCS.
=> Return full asset on Manifest get

src/IIIFPresentation/API.Tests/Features/Manifest/Validators/PresentationManifestValidatorTests.cs, src/IIIFPresentation/API.Tests/Integration/ModifyManifestAssetCreationTests.cs, src/IIIFPresentation/API/Features/Manifest/CanvasPaintingResolver.cs, src/IIIFPresentation/API/Features/Manifest/ManifestWriteService.cs, src/IIIFPresentation/API/Features/Manifest/Validators/PresentationManifestValidator.cs, src/IIIFPresentation/BackgroundHandler.Tests/BatchCompletion/BatchCompletionMessageHandlerTests.cs, src/IIIFPresentation/BackgroundHandler.Tests/Helpers/ManifestMergerTests.cs, src/IIIFPresentation/BackgroundHandler/BatchCompletion/BatchCompletionMessageHandler.cs, src/IIIFPresentation/BackgroundHandler/Helpers/ManifestMerger.cs, src/IIIFPresentation/BackgroundHandler/Helpers/ManifestX.cs, src/IIIFPresentation/BackgroundHandler/Settings/BackgroundHandlerSettings.cs, src/IIIFPresentation/Models/API/Manifest/PresentationManifest.cs, src/IIIFPresentation/Models/Models.csproj
Resolves #204
This PR essentially enables manifests with choiceOrder to be created
It has 2 parts:
- Updates to the API to reject invalid `canvasOrder` and `choiceOrder` combinations
- If there are duplicate `canvasOrder` values these must all have a `choiceOrder` value and each `choiceOrder` must be unique.
- If any `paintedResource` has a `canvas_order` then _all_ items must have a canvas_order.
- allowing canvasOrder to be set directly on a `canvasPainting`, rather than inferred by the order of the assets
- Updates to the background handler to be able to handle valid `canvasOrder` and `choiceOrder` combinations
- labels translated from canvas painting to item in `choiceOrder` - choosing the label of the first item as overall labels
- using the size of the first asset as the size of the …
=> Allowing `choiceOrder` to work in an `asset` request and improvements to `canvasOrder`

src/IIIFPresentation/API.Tests/Integration/GetManifestTests.cs, src/IIIFPresentation/API.Tests/Integration/ModifyManifestAssetCreationTests.cs, src/IIIFPresentation/API.Tests/Integration/ModifyManifestCreateTests.cs, src/IIIFPresentation/API/Attributes/EtagCachingAttribute.cs, src/IIIFPresentation/API/Features/Manifest/CanvasPaintingResolver.cs, src/IIIFPresentation/API/Features/Manifest/ManifestController.cs, src/IIIFPresentation/API/Features/Manifest/ManifestReadService.cs, src/IIIFPresentation/API/Features/Manifest/ManifestWriteService.cs, src/IIIFPresentation/API/Features/Manifest/Requests/DeleteManifest.cs, src/IIIFPresentation/API/Features/Manifest/Requests/GetManifest.cs, src/IIIFPresentation/API/Features/Manifest/Requests/GetManifestHierarchical.cs, src/IIIFPresentation/API/Features/Storage/Helpers/PresentationContextX.cs, src/IIIFPresentation/API/Features/Storage/StorageController.cs, src/IIIFPresentation/API/Infrastructure/ControllerBaseX.cs, src/IIIFPresentation/BackgroundHandler.Tests/BatchCompletion/BatchCompletionMessageHandlerTests.cs, src/IIIFPresentation/BackgroundHandler/BatchCompletion/BatchCompletionMessageHandler.cs, src/IIIFPresentation/Core/WriteResult.cs, src/IIIFPresentation/Models/API/Manifest/PresentationManifest.cs, src/IIIFPresentation/Models/Database/Collections/Manifest.cs, src/IIIFPresentation/Repository/Helpers/CollectionRetrieval.cs, src/IIIFPresentation/Repository/Migrations/20250128103132_addIngestedToManifest.Designer.cs, src/IIIFPresentation/Repository/Migrations/20250128103132_addIngestedToManifest.cs, src/IIIFPresentation/Repository/Migrations/20250203165736_changeIngestedToProcessed.Designer.cs, src/IIIFPresentation/Repository/Migrations/20250203165736_changeIngestedToProcessed.cs, src/IIIFPresentation/Test.Helpers/Helpers/DatabaseTestDataPopulation.cs, src/IIIFPresentation/Test.Helpers/Integration/PresentationContextFixture.cs
Resolves #230 
This PR does the following
- modifies `GET` manifest to return an `Accepted` status code when assets are ingested
- adds an additional `Ingested` property to the database, denoting that the manifest has been ingested at some point in the past
- Modifies the GET hierarchical call to return `NotFound` if the manifest is ingesting, unless it has previously been ingested
=> setting status code to Accepted when ingesting

src/IIIFPresentation/BackgroundHandler.Tests/Helpers/ManifestMergerTests.cs, src/IIIFPresentation/BackgroundHandler/BatchCompletion/BatchCompletionMessageHandler.cs, src/IIIFPresentation/BackgroundHandler/Helpers/ManifestMerger.cs, src/IIIFPresentation/Models/DLCS/AssetId.cs
Fixes #250
Update background handler logic to never set the manifest-level thumbnail from NamedQuery.
=> Don't set manifest thumbnail from named query

src/IIIFPresentation/API.Tests/Converters/CollectionConverterTests.cs, src/IIIFPresentation/API.Tests/Converters/ManifestConverterTests.cs, src/IIIFPresentation/API.Tests/Converters/Streaming/S3StoredJsonProcessorTests.cs, src/IIIFPresentation/API.Tests/Helpers/TestPathGenerator.cs, src/IIIFPresentation/API.Tests/Infrastructure/Validation/PresentationValidationTests.cs, src/IIIFPresentation/API/Converters/CollectionConverter.cs, src/IIIFPresentation/API/Converters/ManifestConverter.cs, src/IIIFPresentation/API/Features/Manifest/ManifestReadService.cs, src/IIIFPresentation/API/Features/Manifest/ManifestWriteService.cs, src/IIIFPresentation/API/Features/Manifest/Requests/GetManifestHierarchical.cs, src/IIIFPresentation/API/Features/Storage/CollectionController.cs, src/IIIFPresentation/API/Features/Storage/Requests/CreateCollection.cs, src/IIIFPresentation/API/Features/Storage/Requests/GetCollection.cs, src/IIIFPresentation/API/Features/Storage/Requests/GetHierarchicalCollection.cs, src/IIIFPresentation/API/Features/Storage/Requests/PostHierarchicalCollection.cs, src/IIIFPresentation/API/Features/Storage/Requests/UpsertCollection.cs, src/IIIFPresentation/API/Features/Storage/StorageController.cs, src/IIIFPresentation/API/Helpers/HttpRequestBasedPathGenerator.cs, src/IIIFPresentation/API/Infrastructure/Validation/PresentationValidation.cs, src/IIIFPresentation/API/Program.cs, src/IIIFPresentation/AWS.Tests/Helpers/BucketHelperTests.cs, src/IIIFPresentation/BackgroundHandler.Tests/BatchCompletion/BatchCompletionMessageHandlerTests.cs, src/IIIFPresentation/BackgroundHandler/BatchCompletion/BatchCompletionMessageHandler.cs, src/IIIFPresentation/BackgroundHandler/Helpers/SettingsBasedPathGenerator.cs, src/IIIFPresentation/BackgroundHandler/Program.cs, src/IIIFPresentation/BackgroundHandler/appsettings.Example.json, src/IIIFPresentation/Repository.Tests/Paths/PathGeneratorTests.cs, src/IIIFPresentation/Repository/Paths/IPathGenerator.cs, src/IIIFPresentation/Repository/Paths/PathGeneratorBase.cs
The final Manifest saved to S3 by the `BackgroundHandler` had the incorrect path - it was using the hierarchical path, rather than the flat path. It was also building the path manually, rather than using `IPathGenerator` logic. Noticed when fixing #250 (PR #260).
Fix involved:
* Moving `IPathGenerator` to `Repository` project
* Adding `abstract class PathGeneratorBase : IPathGenerator`. This has the logic for building paths and requires 2 props - `PresentationUrl` and `DlcsApiUrl`
* Adding `HttpRequestBasedPathGenerator : PathGeneratorBase`, which uses current http context as `PresentationUrl` (this replaces the previous `PathGenerator` in `API`
* Adding `SettingsBasedPathGenerator : PathGeneratorBase`, which is new for `BackgroundHandler` and uses appSettings for `PresentationUrl`
Both …
=> Set correct 'id' in manifest saved to s3

src/IIIFPresentation/API/API.csproj, src/IIIFPresentation/Core/Core.csproj, src/IIIFPresentation/Models/Models.csproj, src/IIIFPresentation/Repository/Repository.csproj
Resolves #251
Resolves #253
This PR updates iiif-net to the latest version, which has support for `navPlace` and better handling of  a `TextualBody` within an `Annotation`
=> Update iiif-net to the latest version

src/IIIFPresentation/API.Tests/Integration/ModifyCollectionTests.cs, src/IIIFPresentation/API/Features/Storage/Requests/UpsertCollection.cs
Fix bug where POST followed by PUT on collection could result in update not requiring eTag. This was due to how eTags are cached, look up doesn't find anything so checks provided value against found value (`null == null`) which passes.
Fixes #276
=> Require eTag when updating collection

src/IIIFPresentation/API.Tests/Integration/GetManifestTests.cs, src/IIIFPresentation/API.Tests/Integration/ModifyManifestAssetCreationTests.cs, src/IIIFPresentation/API/Converters/ManifestConverter.cs, src/IIIFPresentation/API/Features/Manifest/ManifestController.cs, src/IIIFPresentation/API/Features/Manifest/ManifestReadService.cs, src/IIIFPresentation/Models/API/Manifest/PresentationManifest.cs
Resolves #202
This PR adds the `ingesting` property to a manifest, which should look something like this:
```
"ingesting": {
"total": 10,
"finished": 7,
"error": 1
}
```
=> Adding ingesting property onto a manifest

src/IIIFPresentation/API.Tests/Integration/GetCollectionTests.cs, src/IIIFPresentation/API/Converters/DescriptionResourceConverter.cs, src/IIIFPresentation/API/Features/Manifest/Helpers/ErrorHelper.cs, src/IIIFPresentation/API/Features/Manifest/ManifestController.cs, src/IIIFPresentation/API/Features/Manifest/Requests/GetManifestHierarchical.cs, src/IIIFPresentation/API/Features/Storage/CollectionController.cs, src/IIIFPresentation/API/Features/Storage/Helpers/ErrorHelper.cs, src/IIIFPresentation/API/Features/Storage/Helpers/PresentationContextX.cs, src/IIIFPresentation/API/Features/Storage/Models/CollectionWithItems.cs, src/IIIFPresentation/API/Features/Storage/Requests/GetHierarchicalCollection.cs, src/IIIFPresentation/API/Features/Storage/StorageController.cs, src/IIIFPresentation/API/Infrastructure/ControllerBaseX.cs, src/IIIFPresentation/API/Infrastructure/PresentationController.cs, src/IIIFPresentation/API/Infrastructure/Requests/ModifyEntityResult.cs, src/IIIFPresentation/Core/Helpers/GuardX.cs
Add `ControllerBaseX.PresentationContent()` that takes description resource and uses the `.AsJson()` serialiser helper from iiif-net. This ensures consitent serialisation behaviours and uses the [serialisation helpers](https://github.com/digirati-co-uk/iiif-net?tab=readme-ov-file#serialisation) from that library. 
Everything we return from the API is either a Manifest or Collection, so they will all inherit from `JsonLdBase` so a lot of this PR is updating generic constraints to use `JsonLdBase`, rather than `class`.
Fixes #154 
Fixes #156
=> Add helpers for consistent serialisation

src/IIIFPresentation/API.Tests/Converters/CollectionConverterTests.cs, src/IIIFPresentation/API.Tests/Integration/GetCollectionTests.cs, src/IIIFPresentation/API/Converters/CollectionConverter.cs, src/IIIFPresentation/API/Features/Manifest/Requests/GetManifestHierarchical.cs, src/IIIFPresentation/API/Features/Storage/Requests/CreateCollection.cs, src/IIIFPresentation/API/Features/Storage/Requests/GetCollection.cs, src/IIIFPresentation/API/Features/Storage/Requests/GetHierarchicalCollection.cs, src/IIIFPresentation/API/Features/Storage/Requests/PostHierarchicalCollection.cs, src/IIIFPresentation/API/Features/Storage/Requests/UpsertCollection.cs, src/IIIFPresentation/API/Features/Storage/StorageController.cs, src/IIIFPresentation/Models/Database/Collections/Collection.cs, src/IIIFPresentation/Repository.Tests/Paths/PathGeneratorTests.cs, src/IIIFPresentation/Repository/Helpers/HierarchyHelper.cs, src/IIIFPresentation/Repository/Helpers/ManifestRetrieval.cs, src/IIIFPresentation/Repository/Paths/IPathGenerator.cs, src/IIIFPresentation/Repository/Paths/PathGeneratorBase.cs
Resolves #281 
This PR fixes an issue where a IIIF collection retrieved hierarchically sets the `id` of the collection to that of the `root`, rather than the correct ID
Additionally, a refactor has taken place to remove `FullPath` from `Collection` due to the duplicate property on `Hierarchy`
=> Set the full path correctly for a hierarchical IIIF request

src/IIIFPresentation/API.Tests/Integration/ModifyManifestAssetCreationTests.cs, src/IIIFPresentation/API.Tests/Integration/ModifyManifestCreateTests.cs, src/IIIFPresentation/API/Features/Manifest/DlcsManifestCoordinator.cs, src/IIIFPresentation/DLCS.Tests/API/DlcsApiClientTests.cs, src/IIIFPresentation/DLCS.Tests/API/DlcsOrchestratorClientTests.cs, src/IIIFPresentation/DLCS/API/DlcsApiClient.cs, src/IIIFPresentation/DLCS/API/DlcsHttpContent.cs, src/IIIFPresentation/DLCS/Exceptions/DlcsException.cs
Resolves #257
This PR allows a status code to be passed out from a DLCS exception, which can then be used by various callers to correctly set a response status code
=> Allow status code to be passed in a DLCS exception

src/IIIFPresentation/BackgroundHandler.Tests/Helpers/ManifestMergerTests.cs, src/IIIFPresentation/BackgroundHandler/Helpers/ManifestMerger.cs
Resolves #258 
This PR allows the canvas thumbnail to be set in a `choice` construct from a named query
=> Set the thumbnail correctly in a choice order

src/IIIFPresentation/API.Tests/Features/Manifest/Validators/PresentationManifestValidatorTests.cs, src/IIIFPresentation/API/Features/Manifest/CanvasPaintingResolver.cs, src/IIIFPresentation/API/Features/Manifest/Validators/PresentationManifestValidator.cs, src/IIIFPresentation/BackgroundHandler.Tests/BatchCompletion/BatchCompletionMessageHandlerTests.cs, src/IIIFPresentation/BackgroundHandler/BatchCompletion/BatchCompletionMessageHandler.cs, src/IIIFPresentation/BackgroundHandler/Helpers/ImageX.cs, src/IIIFPresentation/BackgroundHandler/Helpers/ManifestX.cs, src/IIIFPresentation/BackgroundHandler/Helpers/ServiceListX.cs, src/IIIFPresentation/Repository.Tests/Paths/PathGeneratorTests.cs, src/IIIFPresentation/Repository/Paths/IPathGenerator.cs, src/IIIFPresentation/Repository/Paths/PathGeneratorBase.cs, src/IIIFPresentation/Test.Helpers/Helpers/DatabaseTestDataPopulation.cs
Implements changes described in #232 
---
- **Use `ImageService` w+h instead of `Canvas` w+h**
- **Validate that `static_width` is paired with `static_height` for `canvasPainting`**
- **Add `GetModifiedImageRequest` to `PathGenerator`**
- **In `BatchCompletionMessageHandler` handle static image sizes**
- **Add tests to cover #232 changes**
- **Handle fully qualified uris in `GetModifiedImageRequest`**
---
Code includes explanatory comments because it is neither obvious nor trivial.
To modify the `ImageRequest` size one has to know customer id and space id. While customer id is provided, space id is in theory optional.
While possible to manually deduce the space id from the existing image id, it feels like it is a bad idea to me, hence the image resizing will only happen if we have …
=> Impl #232 - static image width/height handling

src/IIIFPresentation/API.Tests/Integration/ModifyManifestUpdateTests.cs, src/IIIFPresentation/API/Features/Manifest/ManifestController.cs, src/IIIFPresentation/API/Infrastructure/PresentationController.cs, src/IIIFPresentation/Models/API/General/ModifyCollectionType.cs
Resolves #176 
Refactors the last sections of the API that use `Problem`, to use `PresentationProblem`, which should sort out the last few areas of the code that don't send a correct `error` response
Additionally, returns a correct error type for a manifest deserialization failure
=> Update API to return common error responses

src/IIIFPresentation/API.Tests/Helpers/PresentationContextXTests.cs, src/IIIFPresentation/API.Tests/Integration/GetCollectionTests.cs, src/IIIFPresentation/API/Features/Storage/Helpers/PresentationContextX.cs, src/IIIFPresentation/Test.Helpers/Integration/PresentationContextFixture.cs
Resolves #288 
This PR makes it so that manifests that have never been processed to not be shown in the items of a hierarchical call for a storage collection
=> Stop processing manifests from being shown in public storage collection views

src/IIIFPresentation/BackgroundHandler.Tests/BatchCompletion/BatchCompletionMessageHandlerTests.cs, src/IIIFPresentation/BackgroundHandler/BatchCompletion/BatchCompletionMessageHandler.cs
Fixes #326 
Sets target to match canvasId. `ManifestMerger` will ensure this value is pulled over to final manifest.
`paintingAnnotation.Target = new Canvas { Id = canvas.Id };` is rendered as just `"target" = "{id}"`, see https://github.com/digirati-co-uk/iiif-net?tab=readme-ov-file#canvas
=> Rewrite NQ target to match canvasId

src/IIIFPresentation/API.Tests/Integration/ModifyManifestAssetUpdateTests.cs, src/IIIFPresentation/API.Tests/Integration/ModifyManifestUpdateTests.cs, src/IIIFPresentation/API/Features/Common/Helpers/ErrorHelper.cs, src/IIIFPresentation/API/Features/Manifest/ManifestWriteService.cs, src/IIIFPresentation/Models/API/General/ModifyCollectionType.cs, src/IIIFPresentation/Test.Helpers/Helpers/DatabaseTestDataPopulation.cs
Resolves #290
This PR makes it so that manifests created without assets cannot have them added on an update as well as vice versa.
=> Disallow switching manifests between assets and items

src/IIIFPresentation/API.Tests/Integration/ModifyManifestAssetUpdateTests.cs, src/IIIFPresentation/API/Features/Manifest/ManifestWriteService.cs
Fixes an issue where assets weren't correctly passed through to the response.  This was due to assets not being correctly passed through to `SetGeneratedFields`
=> Pass assets through to SetGeneratedFields

src/IIIFPresentation/API.Tests/Integration/ModifyManifestAssetUpdateTests.cs, src/IIIFPresentation/API.Tests/Integration/ModifyManifestUpdateTests.cs, src/IIIFPresentation/API/Features/Manifest/ManifestWriteService.cs
This PR allows a manifest to be created as an empty manifest and then updated with either assets or items
=> Allow assets or items in updates to empty manifests

src/IIIFPresentation/API.Tests/Features/Manifest/Validators/PresentationManifestValidatorTests.cs, src/IIIFPresentation/API/Features/Manifest/Validators/PresentationManifestValidator.cs
Resolves #338
This PR disables the `'choiceOrder' cannot be a duplicate within a 'canvasOrder'` check when there are `null` `choiceOrder` values as this error is caught by `'choiceOrder' cannot be null within a duplicate 'canvasOrder'`
=> Fix duplicate canvasOrder error when there are null choice orders

src/IIIFPresentation/API.Tests/Attributes/ETagCachingAttributeTests.cs, src/IIIFPresentation/API/Infrastructure/Helpers/ETagManager.cs, src/IIIFPresentation/API/Infrastructure/Helpers/IETagManager.cs, src/IIIFPresentation/API/Infrastructure/Mediatr/Behaviours/LoggingBehaviour.cs, src/IIIFPresentation/API/Settings/CacheSettings.cs
Tweak `ETagManager` to cache items without an absolute expiry. MemoryCache is configured with a limit and compaction % so these should manage the cleanup when under pressure. 
_Note that we'll need to verify these settings when deploying._
Added trace logging to etag manager to help with issues when deployed. Also tweaked `LoggingBehaviour` to add trace logging for _all_ mediatr requests. Ultimately we want to be more targeted in this but it'll potentially help to see how long various requests are taking - current request logging will show the overall request but this will help to differentiate between the end to end request and just the business logic side (ie not streaming in/out content etc).
=> Increase logging around ETags and requests

src/IIIFPresentation/API.Tests/Integration/GetManifestTests.cs, src/IIIFPresentation/API/Features/Storage/StorageController.cs, src/IIIFPresentation/Test.Helpers/Integration/PresentationContextFixture.cs
Was generating path in method but missing customerId. 
Updated Collection and Manifest redirects to use same `GenerateFlatId()` method (Collection was previously using `GenerateFlatCollectionId()`, which outputs the same value).
Fixes #360
=> Use pathGenerator to get hierarch manifest redirect

src/IIIFPresentation/DLCS.Tests/API/DlcsOrchestratorClientTests.cs, src/IIIFPresentation/DLCS.Tests/DlcsSettingsTests.cs, src/IIIFPresentation/DLCS/API/DlcsOrchestratorClient.cs, src/IIIFPresentation/DLCS/DlcsSettings.cs, src/IIIFPresentation/DLCS/ServiceCollectionX.cs
Resolves #367 
Adds new optional appsetting, which is orchestrator uri per customer:
```json
{
"OrchestratorUri": "https://dlcs.default",
"CustomerOrchestratorUri": {
"7": "https://dlcs.customer7"
}
}
```
Using above, customer 7 would use `https://dlcs.customer7/*` and all other customers `https://dlcs.default`.
This will control which uri the NQ is requested on, which allows for custom path formats to be used (via https://github.com/dlcs/protagonist/issues/983)
=> Allow orchestrator uri to be set per customer

src/IIIFPresentation/API/API.csproj, src/IIIFPresentation/BackgroundHandler.Tests/BatchCompletion/BatchCompletionMessageHandlerTests.cs, src/IIIFPresentation/BackgroundHandler.Tests/Helpers/ManifestTestCreator.cs, src/IIIFPresentation/BackgroundHandler/BatchCompletion/BatchCompletionMessageHandler.cs, src/IIIFPresentation/Core/Core.csproj, src/IIIFPresentation/Models/Models.csproj, src/IIIFPresentation/Repository.Tests/Paths/PathGeneratorTests.cs, src/IIIFPresentation/Repository/Paths/IPathGenerator.cs, src/IIIFPresentation/Repository/Paths/PathGeneratorBase.cs, src/IIIFPresentation/Repository/Repository.csproj
If staticWidth and staticHeight specified, use these to set image id. This handles non-canonical path formats introduced to Protagonist in https://github.com/dlcs/protagonist/issues/983
Follow on from impl for #375
=> Handle alt asset formats for setting w + h

src/IIIFPresentation/BackgroundHandler/BatchCompletion/BatchCompletionMessageHandler.cs
Tweaked existing "Attempting.." message to use same format for batch, customer + manifest should we need to parse with a regex or something.
=> Add timing log for backgroundhandler

src/IIIFPresentation/API.Tests/Integration/ModifyManifestAssetCreationTests.cs, src/IIIFPresentation/API.Tests/Integration/ModifyManifestAssetUpdateTests.cs, src/IIIFPresentation/API/Features/Manifest/DlcsManifestCoordinator.cs, src/IIIFPresentation/API/Features/Manifest/ManifestReadService.cs, src/IIIFPresentation/API/Features/Manifest/ManifestWriteService.cs, src/IIIFPresentation/API/Features/Manifest/Requests/DeleteManifest.cs, src/IIIFPresentation/API/Features/Storage/Requests/CreateCollection.cs, src/IIIFPresentation/API/Features/Storage/Requests/DeleteCollection.cs, src/IIIFPresentation/API/Features/Storage/Requests/GetCollection.cs, src/IIIFPresentation/API/Features/Storage/Requests/PostHierarchicalCollection.cs, src/IIIFPresentation/API/Features/Storage/Requests/UpsertCollection.cs, src/IIIFPresentation/API/Infrastructure/ServiceCollectionX.cs, src/IIIFPresentation/API/Program.cs, src/IIIFPresentation/API/appsettings.Example.json, src/IIIFPresentation/BackgroundHandler.Tests/BatchCompletion/BatchCompletionMessageHandlerTests.cs, src/IIIFPresentation/BackgroundHandler.Tests/BatchCompletion/BatchCompletionPathRewriteTests.cs, src/IIIFPresentation/BackgroundHandler/BatchCompletion/BatchCompletionMessageHandler.cs, src/IIIFPresentation/Core.Tests/Helpers/JObjectXTests.cs, src/IIIFPresentation/Core/Helpers/JObjectX.cs, src/IIIFPresentation/DLCS.Tests/API/DlcsApiClientTests.cs, src/IIIFPresentation/DLCS.Tests/API/DlcsOrchestratorClientTests.cs, src/IIIFPresentation/DLCS/API/DlcsApiClient.cs, src/IIIFPresentation/DLCS/API/DlcsOrchestratorClient.cs, src/IIIFPresentation/DLCS/DLCS.csproj, src/IIIFPresentation/DLCS/DlcsSettings.cs, src/IIIFPresentation/DLCS/Models/BulkPatchAssets.cs, src/IIIFPresentation/Models/API/Manifest/PresentationManifest.cs, src/IIIFPresentation/Services.Tests/Manifests/ManifestPaintedResourceParserTests.cs, src/IIIFPresentation/Services/Manifests/AWS/ManifestS3Manager.cs, src/IIIFPresentation/Services/Manifests/ManifestPaintedResourceParser.cs
Resolves #352
This PR updates the manifest functions to return a full manifest immediately if it is possible to do so.
This will happen if all assets are tracked in the database, tracked by the DLCS, or some combination of the 2.
In order to facilitate this, the API now requires a `OrchestratorUri` to be set in the `DLCS` settings to allow the API to talk to orchestrator.
This means that the settings now looks like this:
```json
"DLCS": {
"ApiUri": "https://api.dlcs.test",
"OrchestratorUri": "https://orchestrator.dlcs.test"
}
```
Additionally, the response status code has been changed to show either `OK` or `Created` instead of `Accepted` when this occurs
Finally, this PR resolves [this](https://github.com/dlcs/iiif-presentation/issues/351#issuecomment-2897572704) comment allowing the …
=> Get fully tracked manifests to return immediately

src/IIIFPresentation/API/API.csproj, src/IIIFPresentation/Core/Core.csproj, src/IIIFPresentation/Models/Models.csproj, src/IIIFPresentation/Repository/Manifests/ManifestItemsParser.cs, src/IIIFPresentation/Repository/Repository.csproj
Resolves #410
Upgrades the iiif-net package to the latest version to add in fixes for https://github.com/digirati-co-uk/iiif-net/issues/69 and https://github.com/digirati-co-uk/iiif-net/issues/74
> [!note]
>  this PR [here](https://github.com/dlcs/iiif-presentation/pull/414) is the same as this PR, but it's retargeting to `main`
=> Update iiif-net to 0.3.8

src/IIIFPresentation/API.Tests/Integration/ModifyManifestAssetCreationTests.cs, src/IIIFPresentation/API/API.csproj, src/IIIFPresentation/Core/Core.csproj, src/IIIFPresentation/Models/Models.csproj, src/IIIFPresentation/Repository/Repository.csproj, src/IIIFPresentation/Services/Manifests/ManifestItemsParser.cs, src/IIIFPresentation/Services/Services.csproj
This PR updates the `develop` branch to match changes made in `main`.  This is mainly bringing the version of `iiif-net` up to 0.3.8
pull requests to be merged in:
https://github.com/dlcs/iiif-presentation/pull/416 (already in)
https://github.com/dlcs/iiif-presentation/pull/415
=> Update develop to match main

src/IIIFPresentation/API.Tests/Integration/ModifyRewrittenPathTests.cs, src/IIIFPresentation/Repository.Tests/Paths/PathParserTests.cs, src/IIIFPresentation/Repository.Tests/Paths/PathRewriteParserTests.cs, src/IIIFPresentation/Repository/Paths/PathParser.cs, src/IIIFPresentation/Services.Tests/Manifests/ManifestPaintedResourceParserTests.cs, src/IIIFPresentation/Services/Manifests/ManifestPaintedResourceParser.cs, src/IIIFPresentation/Test.Helpers/Helpers/PathRewriteOptions.cs
Resolves #435
Fixes the API to accept a rewritten `canvasId` to correctly set the value
=> Allow the canvas id to be successfully picked up from rewritten paths

README.md
Updates the README with details of the `manifest-query` named query, to replace the previous `batch-query` documentation
Additionally, the stage, trial and shared environment have been updated to have this named query set
=> Update README with the new named query documentation

src/IIIFPresentation/API.Tests/Integration/ModifyManifestAssetUpdateTests.cs, src/IIIFPresentation/API/Features/Manifest/ManifestWriteService.cs
Resolves #454 
This PR fixes an issue where the database is not saved when all assets are tracked
=> Fix database not being saved when all assets are tracked

src/IIIFPresentation/API.Tests/Integration/ModifyManifestAssetReingestion.cs, src/IIIFPresentation/API/Features/Manifest/ManagedAssetResultFinder.cs, src/IIIFPresentation/Models/API/Manifest/PresentationManifest.cs
Resolves #446 
This PR makes it so that the `reingest` property will still be accepted, but won't show up on the response body.
=> Allow reingest property to be deserialized, but not serialized

docs/.vscode/settings.json, docs/notes/canvas-id-parsing.md, docs/notes/readme.md
This PR adds some notes on how a canvas id is parsed from the payload.  It contains information from #456, so will not be fully accurate until that PR is merged
=> Add canvas id parsing notes
